language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 14
os:
  - linux
script:
  - yarn test:full
  - cat docs/stats/complexity
